Apply.create!([
  {first_name: "Ryan", last_name: "Back", email: "ryan@ryan.com", phone_number: "4157704228", skills: "wad", street_address: "409 NW Tork Place", city: "Hillsboro", state: "OR", zip_code: "97006", resume_file_name: nil, resume_content_type: nil, resume_file_size: nil, resume_updated_at: nil, cover_letter_file_name: nil, cover_letter_content_type: nil, cover_letter_file_size: nil, cover_letter_updated_at: nil, job_id: 1, user_id: 1},
  {first_name: "Ryan", last_name: "Back", email: "ryan@ryan.com", phone_number: "4157704228", skills: "asafs", street_address: "409 NW Tork Place", city: "Hillsboro", state: "OR", zip_code: "97006", resume_file_name: nil, resume_content_type: nil, resume_file_size: nil, resume_updated_at: nil, cover_letter_file_name: nil, cover_letter_content_type: nil, cover_letter_file_size: nil, cover_letter_updated_at: nil, job_id: 2, user_id: 1}
])
Job.create!([
  {title: "Junior Web Developer", location: "Portland, OR", job_type: "Direct Hire", compensation: "50,000", description: "In need of a Ruby on Rails developer.", duration: "", skills: "Ruby on Rails, Version Control, Git"},
  {title: "IT Specialist", location: "Hillsboro, OR", job_type: "Contract", compensation: "20/hr", description: "In need of a linux professional", duration: "6 Months", skills: "Linux, Bash"},
  {title: "Recruiter", location: "Tigard, OR", job_type: "Temp to Hire", compensation: "25/hr", description: "In need of an HR recruiter.", duration: "", skills: "People Person, Microsoft Office"},
  {title: "Junior Web Developer", location: "Portland, OR", job_type: "Contract", compensation: "30/hr", description: "Must know CSS", duration: "1 year", skills: "Sass, Bootstrap, Animations"}
])
User.create!([
  {email: "laura@laura.com", password: 'laura23', first_name: "Laura", last_name: "Back", phone_number: "4156948834", skills: "Recruiting, OnBoarding, Interviews", admin: false, reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, street_address: "409 NW Tork Place", city: "Hillsboro", state: "OR", phone_carrier: "t-mobile", zip_code: "97006", resume_file_name: nil, resume_content_type: nil, resume_file_size: nil, resume_updated_at: nil, cover_letter_file_name: nil, cover_letter_content_type: nil, cover_letter_file_size: nil, cover_letter_updated_at: nil},
  {email: "nancy@nancy.com", password: 'nancy23', first_name: "Nancy", last_name: "McGuire-Back", phone_number: "9167686544", skills: "Management, Excel", admin: false, reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, street_address: "1222 Cherry Blossom Lane", city: "Lincoln", state: "CA", phone_carrier: "at&t", zip_code: "95648", resume_file_name: nil, resume_content_type: nil, resume_file_size: nil, resume_updated_at: nil, cover_letter_file_name: nil, cover_letter_content_type: nil, cover_letter_file_size: nil, cover_letter_updated_at: nil},
  {email: "mike@mike.com", password: 'mike23', first_name: "Mike", last_name: "McGuire-Back", phone_number: "9167181761", skills: "Management", admin: false, reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-03-08 18:36:39", last_sign_in_at: "2017-03-08 18:36:39", current_sign_in_ip: "::1", last_sign_in_ip: "::1", street_address: "1222 Cherry Blossom Lane", city: "Lincoln", state: "CA", phone_carrier: "at&t", zip_code: "95648", resume_file_name: nil, resume_content_type: nil, resume_file_size: nil, resume_updated_at: nil, cover_letter_file_name: nil, cover_letter_content_type: nil, cover_letter_file_size: nil, cover_letter_updated_at: nil},
  {email: "admin@admin.com", password: 'admin23', first_name: "Ryan", last_name: "Back", phone_number: "4157704228", skills: nil, admin: true, reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 7, current_sign_in_at: "2017-03-08 22:01:24", last_sign_in_at: "2017-03-08 22:00:34", current_sign_in_ip: "::1", last_sign_in_ip: "::1", street_address: "409 NW Tork Place", city: "Hillsboro", state: "OR", phone_carrier: "at&t", zip_code: "97006", resume_file_name: nil, resume_content_type: nil, resume_file_size: nil, resume_updated_at: nil, cover_letter_file_name: nil, cover_letter_content_type: nil, cover_letter_file_size: nil, cover_letter_updated_at: nil}
])
